spring.application.name=mplan

spring.datasource.url=jdbc:postgresql://localhost:5432/mplan
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
